[http]
    [http.routers]

        [http.routers.api-router]
            rule = "Host(`example.com`) && Path(`/dashboard`)"
            entryPoints = ["web-secure"]
            middlewares = ["user-auth"]
            service = "api@internal"
            
            [http.routers.api-router.tls]
                certResolver = "myresolver"

        [http.routers.grafana-router]
            rule = "Host(`demo.iotstack.co`) && Path(`/grafana`)"
            entryPoints = ["web-secure"]
            middlewares = ["grafana-mw"]
            service = "grafana"

            [http.routers.grafana-router.tls]
                certResolver = "myresolver"
        
        [http.routers.influxdb-router]
            rule = "PathPrefix(`/influxdb`)"
            entryPoints = ["web-secure"]
            middlewares = ["influxdb-mw"]
            service = "influxdb"

            [http.routers.influxdb-router.tls]
                certResolver = "myresolver"