[http]
    [http.routers]

        [http.routers.api-router]
            rule = "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
            entryPoints = ["web-secure"]
            middlewares = ["user-auth"]
            service = "api@internal"
            
            [http.routers.api-router.tls]

        [http.routers.grafana-router]
            rule = "PathPrefix(`/grafana`)"
            entryPoints = ["web-secure"]
            middlewares = ["grafana-mw"]
            service = "grafana"

            [http.routers.grafana-router.tls]
        
        [http.routers.influxdb-router]
            rule = "PathPrefix(`/influxdb`)"
            entryPoints = ["web-secure"]
            middlewares = ["influxdb-mw"]
            service = "influxdb"

            [http.routers.influxdb-router.tls]