[tcp]
    [tcp.routers]
        [tcp.routers.mqtt-router]
            entryPoints = ["mqtt"]
            service = "mosquitto"
            rule = "HostSNI(`mqtt.demo1.iotstack.co`)"

            [tcp.routers.mqtt-router.tls]
                certResolver = "myresolver"
		passthrough = true

        [tcp.routers.mqtt-websockets-router]
            entryPoints = ["websockets"]
            service = "mosquitto-ws"
            rule = "HostSNI(`mqtt.demo1.iotstack.co`)"

            [tcp.routers.mqtt-websockets-router.tls]
		certResolver = "myresolver"
                passthrough = true