[tcp]
    [tcp.routers]
        [tcp.routers.mqtt-router]
            entryPoints = ["mqtt"]
            service = "mosquitto"
            rule = "HostSNI(`*`)"

            [tcp.routers.mqtt-router.tls]
                options = "mqtts"
                passthrough = true

        [tcp.routers.mqtt-websockets-router]
            entryPoints = ["websockets"]
            service = "mosquitto-ws"
            rule = "HostSNI(`*`)"

            [tcp.routers.mqtt-websockets-router.tls]
                options = ["mqtt-wss"]
                passthrough = true