# Traefik Static Configuration Reference
# Link: https://doc.traefik.io/traefik/reference/static-configuration/file/

[global]
    checkNewVersion = false
    sendAnonymousUsage = true

[api]
    # insecure = true
    dashboard = true
    debug = true

[metrics]
    [metrics.influxDB]
        address = "influxdb:8089"
        protocol = "udp"
        pushInterval = "42s"
        # Same as that of the environment file
        database = "traefik"
        username = "admin"
        password = "tiguitto"
        addEntryPointsLabels = true
        addServicesLabels = true

[log]
    level = "DEBUG"

[accessLog]
    filePath = "/log/access.log"
    bufferingSize = 100
    [accessLog.filters]
        statusCodes = ["200", "300-302", "400-499"]
        retryAttempts = true
        minDuration = 10

[entryPoints]
    [entryPoints.web]
        address = ":80"
        [entryPoints.web.http]
            [entryPoints.web.http.redirections]
                [entryPoints.web.http.redirections.entryPoint]
                    to = "web-secure"
                    scheme = "https"

    [entryPoints.web-secure]
        address = ":443"
        
    [entryPoints.mqtt]
        address = ":8883"
    [entryPoints.websockets]
        address = ":8884"

[providers]
    [providers.docker]
        endpoint = "unix:///var/run/docker.sock"
        exposedByDefault = false
        domain = "demo1.iotstack.co"
        watch = true
        network = "iotstack"
    [providers.file]
        directory = "/etc/traefik/configurations/"
        watch = true

[certificatesResolvers.myresolver.acme]
  email = "lewandowski@swms.de"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"